MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "training_dir/fsfcos_0918_close/model_0040000.pth" #"pretrain_models/R-50.pkl" #"training_dir/fsfcos_0918_close/model_0040000.pth"
  RPN_ONLY: False
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    CENTER_SAMPLE: True
    POS_RADIUS: 1.5
    LOC_LOSS_TYPE: "giou"
    NUM_CLASSES: 2
  RPN:
    USE_FPN: True
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.125, 0.0625, 0.03125, 0.015625, 0.0078125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2ROIFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
DATASETS:
  TRAIN: ("coco_2017_train", ) # ("voc_2012_val_cocostyle",)  #TODO
  TEST:  ("voc_2007_test_cocostyle",) # ("coco_2017_val", )
INPUT:
  MIN_SIZE_TRAIN: (800,)
  SUPP_MIN_SIZE_TRAIN: (200,)
  MAX_SIZE_TRAIN: 1200
  SUPP_MAX_SIZE_TRAIN: 400
  MIN_SIZE_TEST: 800
  SUPP_MIN_SIZE_TEST: 200
  MAX_SIZE_TEST: 1200
  SUPP_MAX_SIZE_TEST: 400
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0004
  WEIGHT_DECAY: 0.000004
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 8 #TODO
  WARMUP_METHOD: "constant"
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 1000
FEW_SHOT:
  UNLOAD_KEYWORD: ()
  UNTRAINED_KEYWORD: ()
  NEG_SUPPORT:
    TURN_ON: False
  CHOOSE_CLOSE: True 
  NUM_SHOT: 1
  SECOND_STAGE_METHOD: 'concat'
  POOLING: 'ROI'
  LOAD_PRETRIANED_RPN_ONLY: False
  RESUME: False
LOSS:
  CLS_LOSS: 'BINARY'
  FOCAL_LOSS: 'SIGMOID'